apiVersion: v1
kind: Service
metadata:
  labels:
    app: poc-hello-java-8
  name: poc-hello-java-8
spec:
  ports:
    - name: poc-hello-java-8
      port: 8087
      protocol: TCP
      targetPort: 8087
  selector:
    app: poc-hello-java-8
  type: NodePort
