apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-hello-java-8
  labels:
    app: poc-hello-java-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-hello-java-8
  template:
    metadata:
      labels:
        app: poc-hello-java-8
        version: v1
    spec:
      containers:
        - name: poc-hello-java-8
          image: 552326470498.dkr.ecr.us-east-2.amazonaws.com/poc-hello-java-8:${imageTag}
          command: ["/bin/sh", "-c",
                    "java -jar poc-hello-java-8.jar
                    --spring.config.additional-location=${SPRING_CONFIG_ADDITIONAL_LOCATION}
                    --jasypt.encryptor.password=sujithes --java.security.egd=file:/dev/./urandom"]
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 700m
              memory: 512Mi
          readinessProbe:
            httpGet:
              port: 8087
              path: /actuator/health/readiness
          livenessProbe:
            httpGet:
              port: 8087
              path: /actuator/health/liveness
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "/deployments/config/application-common.yml,/deployments/config/application-dev.yml"
          volumeMounts:
            - name: common-config
              mountPath: /deployments/config/application-common.yml
              subPath: application-common.yml
            - name: env-config
              mountPath: /deployments/config/application-dev.yml
              subPath: application-dev.yml
      volumes:
        - name: common-config
          configMap:
            name: hello-java-common-configmap
        - name: env-config
          configMap:
            name: hello-java-dev-configmap
